import { Theme } from "../core/Theme.slint";

export component Pill inherits Rectangle {
    in property <string> text: "Pill";
    in property <int> variant: 0;

    min-width: max(pill-text.preferred-width + 16px, 48px);
    height: 24px;
    background: #00000000;
    border-radius: 12px;
    border-width: 1px;
    border-color: variant == 0 ? Theme.accent : (variant == 1 ? Theme.success : (variant == 2 ? Theme.warning : Theme.text-tertiary));
    horizontal-stretch: 0;

    Text {
        x: (parent.width - self.width) / 2;
        text: root.text;
        color: variant == 0 ? Theme.accent : (variant == 1 ? Theme.success : (variant == 2 ? Theme.warning : Theme.text-tertiary));
        font-size: 11px;
        font-weight: Theme.weight-medium;
        vertical-alignment: center;
        horizontal-alignment: center;
    }

    pill-text := Text { visible: false; text: root.text; }
}
