import { Theme } from "../core/Theme.slint";

export component StatusBadge inherits Rectangle {
    in property <string> label: "";
    in property <int> variant: 0;

    min-width: 20px;
    height: 22px;
    background: variant == 0 ? Theme.state-success : (variant == 1 ? Theme.text-tertiary : (variant == 2 ? Theme.state-warning : Theme.state-error));
    border-radius: self.height / 2;
    horizontal-stretch: 0;

    HorizontalLayout {
        padding-left: Theme.sp-2;
        padding-right: Theme.sp-2;
        spacing: Theme.sp-1;

        Rectangle {
            width: 6px;
            height: 6px;
            y: (parent.height - self.height) / 2;
            background: #ffffff;
            border-radius: Theme.radius-full;
            horizontal-stretch: 0;
        }

        if label != "": Text {
            text: root.label;
            color: #ffffff;
            font-family: Theme.font-ui;
            font-size: Theme.text-xs;
            font-weight: Theme.weight-semibold;
            vertical-alignment: center;
            horizontal-stretch: 1;
        }
    }
}
