import { Theme } from "../core/Theme.slint";

export component TextBadge inherits Rectangle {
    in property <string> label: "";
    in property <int> variant: 0;

    min-width: 24px;
    height: 22px;
    background: variant == 1 ? Theme.accent-subtle : (variant == 2 ? Theme.green_100 : (variant == 3 ? Theme.amber_100 : (variant == 4 ? Theme.red_100 : Theme.bg-overlay)));
    border-radius: Theme.radius-sm;
    horizontal-stretch: 0;

    label-text := Text {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
        text: root.label;
        color: variant == 1 ? Theme.accent : (variant == 2 ? Theme.green_700 : (variant == 3 ? Theme.amber_600 : (variant == 4 ? Theme.red_600 : Theme.text-secondary)));
        font-family: Theme.font-ui;
        font-size: Theme.text-xs;
        font-weight: Theme.weight-semibold;
        vertical-alignment: center;
        horizontal-alignment: center;
    }
}
