import { Theme } from "../core/Theme.slint";
import { FaIcon } from "../core/FaIcon.slint";

export component BackToTopButton inherits Rectangle {
    width: 48px;
    height: 48px;
    background: Theme.bg-raised;
    border-radius: 24px;
    border-width: 1px;
    border-color: Theme.border-base;
    horizontal-stretch: 0;

    FaIcon {
        source: @image-url("../../fontawesome-free-7.3.0-desktop/svgs/solid/arrow-up.svg");
        fa-size: 18px;
        fa-color: Theme.text-primary;
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
    }

    TouchArea {
        clicked => { }
    }
}
