import { Theme } from "../core/Theme.slint";
import { FaIcon } from "../core/FaIcon.slint";

export component DropdownButton inherits Rectangle {
    in-out property <string> text: "Options";

    background: Theme.bg-raised;
    border-radius: Theme.radius-md;
    border-width: 1px;
    border-color: Theme.border-base;
    height: 40px;
    horizontal-stretch: 1;

    HorizontalLayout {
        padding-left: 16px;
        padding-right: 12px;

        Text {
            text: root.text;
            color: Theme.text-primary;
            font-size: 14px;
            font-weight: Theme.weight-medium;
            vertical-alignment: center;
            horizontal-stretch: 1;
        }

        FaIcon {
            source: @image-url("../../fontawesome-free-7.3.0-desktop/svgs/solid/chevron-down.svg");
            fa-size: 12px;
            fa-color: Theme.text-tertiary;
        }
    }

    TouchArea {
        clicked => { }
    }
}
