import { Theme } from "../core/Theme.slint";

export component FabExtended inherits Rectangle {
    in-out property <string> text: "New item";
    in-out property <bool> enabled: true;

    callback clicked();

    height: 56px;
    background: !enabled ? Theme.btn-disabled-bg : (ta.pressed ? Theme.btn-primary-bg-pressed : (ta.has-hover ? Theme.btn-primary-bg-hover : Theme.accent));
    border-radius: 16px;
    horizontal-stretch: 1;

    animate background { duration: Theme.dur-fast; }

    HorizontalLayout {
        padding-left: 20px;
        padding-right: 20px;
        spacing: 10px;

        Image {
            source: @image-url("../../fontawesome-free-7.3.0-desktop/svgs/solid/plus.svg");
            width: 20px;
            height: 20px;
            y: (parent.height - self.height) / 2;
            colorize: enabled ? #ffffff : Theme.btn-disabled-text;
        }

        Text {
            text: root.text;
            color: enabled ? #ffffff : Theme.btn-disabled-text;
            font-size: 15px;
            font-weight: Theme.weight-semibold;
            vertical-alignment: center;
            horizontal-stretch: 1;
        }
    }

    ta := TouchArea {
        enabled: root.enabled;
        clicked => { root.clicked(); }
    }
}
