import { Theme } from "../core/Theme.slint";

export component FabMini inherits Rectangle {
    in-out property <string> icon: "plus";

    width: 40px;
    height: 40px;
    background: Theme.accent;
    border-radius: 12px;
    horizontal-stretch: 0;

    Image {
        source: @image-url("../../fontawesome-free-7.3.0-desktop/svgs/solid/plus.svg");
        width: 16px;
        height: 16px;
        colorize: #ffffff;
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
    }

    TouchArea {
        clicked => { }
    }
}
