import { Theme } from "../core/Theme.slint";
import { FaIcon } from "../core/FaIcon.slint";

export component GhostButton inherits Rectangle {
    in-out property <string> text: "Ghost";
    in-out property <bool> enabled: true;

    background: transparent;
    border-radius: Theme.radius-md;
    height: 40px;
    horizontal-stretch: 1;

    HorizontalLayout {
        alignment: center;
        spacing: 8px;

        FaIcon {
            source: @image-url("../../fontawesome-free-7.3.0-desktop/svgs/solid/ghost.svg");
            fa-size: 14px;
            fa-color: Theme.text-secondary;
        }

        Text {
            text: root.text;
            color: Theme.text-secondary;
            font-size: 14px;
            font-weight: Theme.weight-semibold;
            vertical-alignment: center;
        }
    }

    TouchArea {
        clicked => { }
    }
}
