import { Theme } from "../core/Theme.slint";
import { FaIcon } from "../core/FaIcon.slint";

export component PrimaryButton inherits Rectangle {
    in-out property <string> text: "Primary";
    in-out property <bool> enabled: true;

    callback clicked();

    background: !enabled ? Theme.btn-disabled-bg : (ta.pressed ? Theme.btn-primary-bg-pressed : (ta.has-hover ? Theme.btn-primary-bg-hover : Theme.accent));
    border-radius: Theme.radius-md;
    height: 40px;
    horizontal-stretch: 1;

    animate background { duration: Theme.dur-fast; }

    HorizontalLayout {
        alignment: center;
        spacing: 8px;

        FaIcon {
            source: @image-url("../../fontawesome-free-7.3.0-desktop/svgs/solid/check.svg");
            fa-size: 14px;
            fa-color: enabled ? #ffffff : Theme.btn-disabled-text;
            y: (parent.height - self.height) / 2;
        }

        Text {
            text: root.text;
            color: enabled ? #ffffff : Theme.btn-disabled-text;
            font-size: 14px;
            font-weight: Theme.weight-semibold;
            vertical-alignment: center;
        }
    }

    ta := TouchArea {
        enabled: root.enabled;
        clicked => { root.clicked(); }
    }
}
