import { Theme } from "../core/Theme.slint";
import { FaIcon } from "../core/FaIcon.slint";
import { FabMini } from "FabMini.slint";

export component SpeedDial inherits Rectangle {
    horizontal-stretch: 0;

    VerticalLayout {
        spacing: 12px;

        FabMini { icon: "pen"; }
        FabMini { icon: "paperclip"; }
        FabMini { icon: "camera"; }
        FabMini { icon: "plus"; }
    }
}
