[package]
name        = "ltk-animation"
description = "LTK animation: timeline, spring, physics, state machines"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
ltk-core    = { path = "../ltk-core" }
ltk-design  = { path = "../ltk-design" }
ltk-state   = { path = "../ltk-state" }
parking_lot = { workspace = true }
smallvec    = { workspace = true }
