//! Serialize themes to TOML / JSON for export / editing.

use super::Theme;
use ltk_core::LtkResult;
use std::path::Path;

/// Exports a theme to disk.
pub struct ThemeSerializer;

impl ThemeSerializer {
    /// Write the theme to a TOML file.
    pub fn to_toml(theme: &Theme, path: &Path) -> LtkResult<()> {
        let content = format!(
            "# LTK Theme: {}\n# Generated by ltk-design\n\n[meta]\nname = {:?}\nmode = {:?}\n",
            theme.name, theme.name, theme.mode
        );
        std::fs::write(path, content)?;
        Ok(())
    }

    /// Emit a CSS custom-property stylesheet (for web tools / Figma export).
    pub fn to_css_vars(theme: &Theme) -> String {
        use crate::color::ColorToken;
        let mut css = String::from(":root {\n");
        for token in [
            ColorToken::Primary, ColorToken::BgBase, ColorToken::BgSurface,
            ColorToken::TextPrimary, ColorToken::TextSecondary,
            ColorToken::BorderBase,
        ] {
            let c = theme.colors.get(token);
            let b = c.to_srgb_bytes();
            css.push_str(&format!(
                "  --ltk-{:?}: #{:02X}{:02X}{:02X};\n",
                token, b[0], b[1], b[2]
            ));
        }
        css.push_str("}\n");
        css
    }
}
