import { Theme } from "../core/Theme.slint";

export component FormGroup inherits Rectangle {
    background: transparent;

    in property <string> label: "";
    in property <bool> required: false;
    in property <bool> disabled: false;
    in property <length> gap: 4px;

    VerticalLayout {
        spacing: gap;

        if label != "": HorizontalLayout {
            spacing: 2px;
            height: 20px;

            Text {
                text: label;
                font-size: Theme.text-sm;
                font-weight: Theme.weight-medium;
                color: Theme.text-primary;
                y: 1px;
            }

            if required: Text {
                text: "*";
                font-size: Theme.text-sm;
                color: Theme.error;
                y: 1px;
            }
        }
    }
}
