import { Theme } from "../core/Theme.slint";
import { FaIcon } from "../core/FaIcon.slint";

export component ShareCountDisplay inherits Rectangle {
    background: transparent;

    in property <int> shares: 128;

    HorizontalLayout {
        spacing: Theme.sp-1;

        FaIcon {
            source: @image-url("../../fontawesome-free-7.3.0-desktop/svgs/solid/arrow-up-right-from-square.svg");
            fa-size: 11px;
            fa-color: Theme.text-tertiary;
            y: (parent.height - self.height) / 2;
        }

        Text {
            text: shares >= 1000 ? Math.round(shares / 100) / 10 + "k" : shares;
            font-size: Theme.text-sm;
            color: Theme.text-tertiary;
            y: 1px;
        }
    }
}
