import { Theme } from "../core/Theme.slint";
import { FaIcon } from "../core/FaIcon.slint";

export component ViewCountDisplay inherits Rectangle {
    background: transparent;

    in property <int> views: 1542;

    HorizontalLayout {
        spacing: Theme.sp-1;

        FaIcon {
            source: @image-url("../../fontawesome-free-7.3.0-desktop/svgs/solid/eye.svg");
            fa-size: 12px;
            fa-color: Theme.text-tertiary;
            y: (parent.height - self.height) / 2;
        }

        Text {
            text: views >= 1000 ? Math.round(views / 100) / 10 + "k" : views;
            font-size: Theme.text-sm;
            color: Theme.text-tertiary;
            y: 1px;
        }
    }
}
