// Border Width tokens
export global BorderWidth {
    out property <length> border-0: 0px;
    out property <length> border-1: 1px;
    out property <length> border-2: 2px;
    out property <length> border-4: 4px;
    out property <length> border-8: 8px;

    // Named
    out property <length> border-thin: 1px;
    out property <length> border-base: 1px;
    out property <length> border-thick: 2px;
    out property <length> border-focus-ring: 2px;
    out property <length> border-indicator: 3px;
}
