// Grid Margin token
export global GridMargin {
    out property <length> margin-0: 0px;
    out property <length> margin-xs: 8px;
    out property <length> margin-sm: 16px;
    out property <length> margin-md: 24px;
    out property <length> margin-lg: 32px;
    out property <length> margin-xl: 48px;
    out property <length> margin-2xl: 64px;
    out property <length> margin-3xl: 96px;
    out property <length> margin-4xl: 128px;
}
