// Grid Columns token
export global GridColumns {
    out property <int> grid-cols-1: 1;
    out property <int> grid-cols-2: 2;
    out property <int> grid-cols-3: 3;
    out property <int> grid-cols-4: 4;
    out property <int> grid-cols-5: 5;
    out property <int> grid-cols-6: 6;
    out property <int> grid-cols-7: 7;
    out property <int> grid-cols-8: 8;
    out property <int> grid-cols-9: 9;
    out property <int> grid-cols-10: 10;
    out property <int> grid-cols-11: 11;
    out property <int> grid-cols-12: 12;
}
