// Icon Size scale
export global IconSize {
    out property <length> icon-2xs: 10px;
    out property <length> icon-xs: 12px;
    out property <length> icon-sm: 14px;
    out property <length> icon-md: 16px;
    out property <length> icon-base: 20px;
    out property <length> icon-lg: 24px;
    out property <length> icon-xl: 32px;
    out property <length> icon-2xl: 40px;
    out property <length> icon-3xl: 48px;
    out property <length> icon-4xl: 64px;
}
