// Typography — Font Weight scale
export global TypographyFontWeight {
    out property <int> weight-thin: 100;
    out property <int> weight-extralight: 200;
    out property <int> weight-light: 300;
    out property <int> weight-regular: 400;
    out property <int> weight-medium: 500;
    out property <int> weight-semibold: 600;
    out property <int> weight-bold: 700;
    out property <int> weight-extrabold: 800;
    out property <int> weight-black: 900;
}
