// Typography — Line Height scale
export global TypographyLineHeight {
    out property <float> leading-none: 1.0;
    out property <float> leading-tight: 1.15;
    out property <float> leading-snug: 1.3;
    out property <float> leading-normal: 1.5;
    out property <float> leading-relaxed: 1.625;
    out property <float> leading-loose: 1.8;
    out property <float> leading-2: 2.0;
    out property <float> leading-2-5: 2.5;
    out property <float> leading-3: 3.0;
}
