// Z-Index layer stack
export global ZIndex {
    out property <int> z-base: 0;
    out property <int> z-raised: 10;
    out property <int> z-dropdown: 100;
    out property <int> z-sticky: 200;
    out property <int> z-header: 300;
    out property <int> z-overlay: 400;
    out property <int> z-modal: 500;
    out property <int> z-popover: 600;
    out property <int> z-toast: 700;
    out property <int> z-tooltip: 800;
    out property <int> z-max: 9999;
}
