import { Theme } from "../core/Theme.slint";

export component CounterNumberTween inherits Rectangle {
    background: transparent;

    in property <int> from-value: 0;
    in property <int> to-value: 100;
    in property <bool> animate: true;

    height: 48px;

    Text {
        text: "\{to-value}";
        font-size: Theme.text-3xl;
        font-weight: Theme.weight-bold;
        color: Theme.text-primary;
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
    }
}
