import { Theme } from "../core/Theme.slint";

export component FlipAnimationHelper inherits Rectangle {
    background: transparent;
    clip: true;

    in property <length> from-x: 0px;
    in property <length> from-y: 0px;
    in property <length> to-x: 0px;
    in property <length> to-y: 0px;
    in property <bool> playing: false;

    content := Rectangle {
        x: playing ? to-x : from-x;
        y: playing ? to-y : from-y;
        background: transparent;
        animate x, y { duration: Theme.dur-slower; easing: Theme.ease-spring; }

        @children
    }
}
