import { Theme } from "../core/Theme.slint";

export component FlipAnimationHelper inherits Rectangle {
    background: transparent;

    in property <length> from-x: 0px;
    in property <length> from-y: 0px;
    in property <length> to-x: 0px;
    in property <length> to-y: 0px;
    in property <bool> playing: false;

    content := Rectangle {
    opacity: playing ? 1 : 0;
    animate opacity { duration: Theme.dur-slower; easing: Theme.ease-spring; }
        background: transparent;
    }
}
