import { Theme } from "../core/Theme.slint";
import { TabButton } from "./TabButton.slint";
import { IconButtonCircle } from "../buttons/IconButtonCircle.slint";

export component TabBar inherits Rectangle {
    in property <[string]> tabs: [];
    in property <int> current-index: 0;
    in property <bool> new-tab-visible: true;

    callback new-tab-clicked();
    callback tab-clicked(int);
    callback tab-close-clicked(int);

    height: 40px;
    background: transparent;

    HorizontalLayout {
        x: 0;
        y: 0;
        width: parent.width;
        height: parent.height;
        spacing: Theme.sp-2;

        for tab[idx] in root.tabs: TabButton {
            horizontal-stretch: 1;
            text: tab;
            checked: idx == root.current-index;
            clicked => { root.tab-clicked(idx); }
            close-clicked => { root.tab-close-clicked(idx); }
        }

        if new-tab-visible: IconButtonCircle {
            width: 32px;
            height: 32px;
            icon: @image-url("../../fontawesome-free-7.3.0-desktop/svgs/solid/plus.svg");
            y: (parent.height - self.height) / 2;
            clicked => { root.new-tab-clicked(); }
        }

        Rectangle { horizontal-stretch: 1; }
    }
}
