import { Theme } from "../core/Theme.slint";

export component RadioButton inherits Rectangle {
    in-out property <bool> selected: false;
    in-out property <bool> enabled: true;
    in-out property <string> label: "Option";
    callback picked();

    height: 32px;
    horizontal-stretch: 1;

    Rectangle {
        x: 0px;
        y: (parent.height - 20px) / 2;
        width: 20px;
        height: 20px;
        border-radius: 10px;
        border-width: 2px;
        border-color: root.selected ? Theme.accent : Theme.border-base;

        if root.selected: Rectangle {
            x: 4px;
            y: 4px;
            width: 12px;
            height: 12px;
            border-radius: 6px;
            background: Theme.accent;
        }
    }

    Text {
        x: 28px;
        y: (parent.height - self.height) / 2;
        text: root.label;
        color: root.enabled ? Theme.text-primary : Theme.text-disabled;
        font-size: 14px;
        vertical-alignment: center;
    }

    TouchArea {
        clicked => {
            if (root.enabled) {
                root.selected = true;
                root.picked();
            }
        }
    }
}
