import { Theme } from "../core/Theme.slint";

export component HueSlider inherits Rectangle {
    in-out property <float> hue: 0;

    height: 20px;
    horizontal-stretch: 1;

    Rectangle {
        y: (parent.height - self.height) / 2;
        height: 12px;
        border-radius: 6px;
        clip: true;

        Rectangle {
            background: #ff0000;
        }

        Rectangle {
            x: parent.width * 0.17;
            background: #ffff00;
            width: parent.width * 0.17;
        }

        Rectangle {
            x: parent.width * 0.33;
            background: #00ff00;
            width: parent.width * 0.17;
        }

        Rectangle {
            x: parent.width * 0.50;
            background: #00ffff;
            width: parent.width * 0.17;
        }

        Rectangle {
            x: parent.width * 0.67;
            background: #0000ff;
            width: parent.width * 0.17;
        }

        Rectangle {
            x: parent.width * 0.83;
            background: #ff00ff;
            width: parent.width * 0.17;
        }
    }

    handle := Rectangle {
        width: 20px;
        height: 20px;
        background: Theme.bg-surface;
        border-width: 3px;
        border-color: #ffffff;
        border-radius: 10px;
        x: max(0, min(parent.width - self.width, root.hue / 360 * parent.width));
        y: (parent.height - self.height) / 2;

        drop-shadow-color: Theme.border-default;
        drop-shadow-blur: 4px;
    }

    TouchArea {
        moved => {
            root.hue = max(0, min(360, (self.mouse-x / parent.width) * 360));
        }
    }
}
