import { Theme } from "../core/Theme.slint";

export component ContentRegion inherits Rectangle {
    background: transparent;

    in property <length> region-max-width: 960px;
    in property <length> region-padding: 24px;

    HorizontalLayout {
        alignment: center;

        Rectangle {
            width: Math.min(parent.width, root.region-max-width);

            HorizontalLayout {
                padding: root.region-padding;
                @children
            }
        }
    }
}
