import { Theme } from "../core/Theme.slint";

export component SingleColumn inherits Rectangle {
    background: transparent;

    in property <length> column-max-width: 720px;
    in property <length> column-padding-x: 24px;

    HorizontalLayout {
        alignment: center;

        Rectangle {
            width: Math.min(parent.width, root.column-max-width);
            background: transparent;

            HorizontalLayout {
                padding-left: root.column-padding-x;
                padding-right: root.column-padding-x;
                @children
            }
        }
    }
}
