import { Theme } from "../core/Theme.slint";

export component SingleColumn inherits Rectangle {
    background: transparent;

    in property <length> column-max-width: 720px;
    in property <int> padding-px: 24;

    HorizontalLayout {
        alignment: center;

        Rectangle {
            width: Math.min(parent.width, root.column-max-width);
            background: transparent;
        }
    }
}
