import { Theme } from "../core/Theme.slint";

export component WaterfallLayout inherits Rectangle {
    background: transparent;
    clip: true;

    in property <int> columns: 3;
    in property <length> gap: 12px;

    Flickable {
        HorizontalLayout {
            spacing: gap;

            for col_idx[ci] in columns: VerticalLayout {
                vertical-stretch: 1;
                spacing: gap;
            }
        }
    }
}
